### ISSUE TITLE
Turf on Server is still supported ?

### ISSUE THREAD

**Issue by geoyogesh** [mapbox/turf-server-example#4]
when i try to install the package from (https://www.npmjs.com/package/turf).. it says package is deprecated.. but this example project is still using that repo...

Just need some clarty on how to use turf.js on backend nodejs server?

**Comment by morganherlocker** [comment]
Hi @geoyogesh, the turf package has been deprecated for sometime in favor of the namespaced `@turf/turf` module. At the time the original module was published, npm did not support namespaces.

https://www.npmjs.com/package/@turf/turf
